http=com.org.creational.abstractFactory.productFactory.impl.HttpResourceLoader
file=com.org.creational.abstractFactory.productFactory.impl.FileResourceLoader
default=com.org.creational.abstractFactory.productFactory.impl.DefaultResourceLoader