http=com.org.creational.factoryMethod.resourceFactory.impl.HttpResourceLoader
file=com.org.creational.factoryMethod.resourceFactory.impl.FileResourceLoader
default=com.org.creational.factoryMethod.resourceFactory.impl.DefaultResourceLoader