#服务器端口
server:
  port: 8160

#数据源配置
#spring:
#  datasource:
#    url: ${ddpay.datasource.user.url}
#    username: ${ddpay.datasource.user.username}
#    password: ${ddpay.datasource.user.password}


management:
  server:
    port: 45678
  endpoints:
    web:
      base-path: /admin
#      exposure:
#        include: /*


